// FontEnd/src/pages/MenuAdmin.tsx
import { useState } from "react";
import { Plus, Search, Edit3, Trash2, Flame, Coffee } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { menuItems as initial, formatVND, categories, MenuItem, Category } from "@/data/menu";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

export default function MenuAdmin() {
  const [items, setItems] = useState<MenuItem[]>(initial);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<Category | "all">("all");
  const [editing, setEditing] = useState<MenuItem | null>(null);
  const [open, setOpen] = useState(false);

  const visible = items.filter(
    (m) =>
      (filter === "all" || m.category === filter) &&
      m.name.toLowerCase().includes(search.toLowerCase())
  );

  const openNew = () => {
    setEditing({
      id: `new-${Date.now()}`,
      name: "",
      description: "",
      price: 0,
      category: "coffee",
      image: items[0].image,
      popular: false,
    });
    setOpen(true);
  };

  const save = () => {
    if (!editing || !editing.name.trim()) {
      toast.error("Vui lòng nhập tên món");
      return;
    }
    setItems((prev) => {
      const exists = prev.find((p) => p.id === editing.id);
      return exists ? prev.map((p) => (p.id === editing.id ? editing : p)) : [editing, ...prev];
    });
    toast.success("Đã lưu món");
    setOpen(false);
  };

  const remove = (id: string) => {
    setItems((prev) => prev.filter((p) => p.id !== id));
    toast.success("Đã xóa món");
  };

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center gap-3 justify-between">
        <div className="relative flex-1 min-w-[220px] max-w-md">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Tìm theo tên món..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9 bg-card border-cream-deep h-10"
          />
        </div>
        <Button onClick={openNew} className="bg-caramel hover:bg-brown text-cream rounded-xl">
          <Plus className="w-4 h-4 mr-1.5" /> Thêm món mới
        </Button>
      </div>

      <div className="flex gap-2 overflow-x-auto scrollbar-none">
        {categories.map((c) => (
          <button
            key={c.id}
            onClick={() => setFilter(c.id as Category | "all")}
            className={`px-3.5 py-1.5 rounded-full text-xs font-medium whitespace-nowrap transition-all ${
              filter === c.id
                ? "bg-espresso text-cream"
                : "bg-card text-espresso border border-cream-deep hover:border-caramel/50"
            }`}
          >
            {c.label}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        {visible.map((m) => (
          <article key={m.id} className="bg-card rounded-2xl border border-cream-deep shadow-card overflow-hidden group">
            <div className="relative aspect-[4/3] overflow-hidden bg-cream-deep">
              <img src={m.image} alt={m.name} loading="lazy" className="w-full h-full object-cover group-hover:scale-105 transition-transform" />
              {m.popular && (
                <span className="absolute top-2 left-2 px-2 py-1 rounded-full bg-espresso/90 text-cream text-[10px] font-semibold flex items-center gap-1">
                  <Flame className="w-3 h-3" /> Bán chạy
                </span>
              )}
              <div className="absolute top-2 right-2 flex gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity">
                <button
                  onClick={() => { setEditing(m); setOpen(true); }}
                  className="w-8 h-8 rounded-full bg-cream/95 text-espresso flex items-center justify-center hover:bg-caramel hover:text-cream"
                >
                  <Edit3 className="w-3.5 h-3.5" />
                </button>
                <button
                  onClick={() => remove(m.id)}
                  className="w-8 h-8 rounded-full bg-cream/95 text-destructive flex items-center justify-center hover:bg-destructive hover:text-cream"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
            <div className="p-3">
              <h3 className="font-display text-espresso font-semibold leading-tight">{m.name}</h3>
              <p className="text-xs text-muted-foreground mt-1 line-clamp-2 min-h-[2rem]">{m.description}</p>
              <div className="flex justify-between items-center mt-2">
                <span className="text-caramel font-semibold">{formatVND(m.price)}</span>
                <span className="text-[10px] uppercase tracking-wide text-muted-foreground bg-cream px-2 py-0.5 rounded-full">
                  {categories.find((c) => c.id === m.category)?.label}
                </span>
              </div>
            </div>
          </article>
        ))}
        {visible.length === 0 && (
          <div className="col-span-full text-center py-16 text-muted-foreground">
            <Coffee className="w-12 h-12 mx-auto mb-2 opacity-40" />
            Không tìm thấy món nào
          </div>
        )}
      </div>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="bg-cream border-cream-deep max-w-lg">
          <DialogHeader>
            <DialogTitle className="font-display text-2xl text-espresso">
              {editing && items.find((i) => i.id === editing.id) ? "Sửa món" : "Thêm món mới"}
            </DialogTitle>
          </DialogHeader>
          {editing && (
            <div className="space-y-4">
              <div className="space-y-1.5">
                <Label className="text-espresso">Tên món</Label>
                <Input
                  value={editing.name}
                  onChange={(e) => setEditing({ ...editing, name: e.target.value })}
                  className="bg-background border-cream-deep"
                  placeholder="Vd: Cappuccino"
                />
              </div>
              <div className="space-y-1.5">
                <Label className="text-espresso">Mô tả</Label>
                <Textarea
                  value={editing.description}
                  onChange={(e) => setEditing({ ...editing, description: e.target.value })}
                  className="bg-background border-cream-deep min-h-[70px]"
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label className="text-espresso">Giá (VND)</Label>
                  <Input
                    type="number"
                    value={editing.price}
                    onChange={(e) => setEditing({ ...editing, price: Number(e.target.value) })}
                    className="bg-background border-cream-deep"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label className="text-espresso">Danh mục</Label>
                  <Select
                    value={editing.category}
                    onValueChange={(v: Category) => setEditing({ ...editing, category: v })}
                  >
                    <SelectTrigger className="bg-background border-cream-deep">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {categories.filter((c) => c.id !== "all").map((c) => (
                        <SelectItem key={c.id} value={c.id}>{c.label}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="flex items-center justify-between p-3 rounded-xl bg-background border border-cream-deep">
                <div>
                  <Label className="text-espresso">Đánh dấu Bán chạy</Label>
                  <p className="text-xs text-muted-foreground mt-0.5">Hiển thị badge nổi bật cho khách</p>
                </div>
                <Switch
                  checked={!!editing.popular}
                  onCheckedChange={(v) => setEditing({ ...editing, popular: v })}
                />
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)} className="border-cream-deep">Hủy</Button>
            <Button onClick={save} className="bg-caramel hover:bg-brown text-cream">Lưu</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// vue-project/src/pages/MenuAdmin.vue
<template>
  <div class="space-y-5 p-6">
    <!-- Header: Search + Button -->
    <div class="flex flex-wrap items-center gap-3 justify-between">
      <div class="relative flex-1 min-w-[220px] max-w-md">
        <Search class="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
        <Input
          placeholder="Tìm theo tên món..."
          v-model="search"
          class="pl-9 bg-card border border-cream-deep shadow-inner h-10 rounded-lg"
        />
      </div>
      <Button @click="openNew" class="bg-caramel text-cream rounded-lg shadow-xl border border-cream-deep/60 px-6 py-2.5 font-semibold flex items-center gap-2">
        <Plus class="w-4 h-4" /> Thêm món mới
      </Button>
    </div>

    <!-- Filter categories -->
    <div class="flex gap-2 overflow-x-auto scrollbar-none pb-1">
      <button
        v-for="c in categories"
        :key="c.id"
        @click="filter = c.id as Category | 'all'"
        :class="[
          'px-5 py-2.5 rounded-lg text-sm font-semibold whitespace-nowrap border shadow-sm',
          filter === c.id
            ? 'bg-espresso text-cream border-espresso shadow-xl'
            : 'bg-card text-espresso border-cream-deep'
        ]"
      >
        {{ c.label }}
      </button>
    </div>

    <!-- Menu grid -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
      <article
        v-for="m in paginatedItems"
        :key="m.id"
        class="bg-card rounded-lg border border-cream-deep shadow-card overflow-hidden flex flex-col"
      >
        <!-- Image area with depth -->
        <div class="relative aspect-[4/3] bg-cream-deep">
          <img
            :src="m.image"
            :alt="m.name"
            loading="lazy"
            class="w-full h-full object-cover"
          />
          <!-- Subtle gradient overlay for depth -->
          <div class="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black/20"></div>

          <!-- Popular badge -->
          <span
            v-if="m.popular"
            class="absolute top-4 left-4 px-4 py-1 rounded-lg bg-espresso/95 text-cream text-xs font-bold flex items-center gap-1 shadow-xl"
          >
            <Flame class="w-3.5 h-3.5" /> Bán chạy
          </span>

          <!-- Action buttons - luôn hiển thị, không hover -->
          <div class="absolute top-4 right-4 flex gap-2">
            <button
              @click="openEdit(m)"
              class="w-9 h-9 rounded-lg bg-cream/95 border border-cream-deep shadow-xl flex items-center justify-center text-espresso hover:bg-caramel hover:text-cream"
            >
              <Edit3 class="w-4 h-4" />
            </button>
            <button
              @click="remove(m.id)"
              class="w-9 h-9 rounded-lg bg-cream/95 border border-cream-deep shadow-xl flex items-center justify-center text-destructive"
            >
              <Trash2 class="w-4 h-4" />
            </button>
          </div>
        </div>

        <!-- Content -->
        <div class="p-5 flex-1 flex flex-col">
          <h3 class="font-display text-espresso text-xl font-semibold leading-tight">{{ m.name }}</h3>
          <p class="text-sm text-muted-foreground mt-2 line-clamp-2 flex-1">{{ m.description }}</p>

          <div class="flex justify-between items-end mt-4">
            <span class="text-2xl font-semibold text-caramel">{{ formatVND(m.price) }}</span>
            <span
              class="text-xs uppercase tracking-widest font-medium px-4 py-1 rounded-lg bg-cream border border-cream-deep text-espresso/70"
            >
              {{ categories.find((c) => c.id === m.category)?.label }}
            </span>
          </div>
        </div>
      </article>

      <!-- Empty state -->
      <div
        v-if="paginatedItems.length === 0"
        class="col-span-full text-center py-20 text-muted-foreground flex flex-col items-center"
      >
        <Coffee class="w-16 h-16 mx-auto mb-4 opacity-30" />
        <p class="text-lg font-medium">Không tìm thấy món nào</p>
      </div>
    </div>

    <!-- Pagination -->
    <div v-if="filteredItems.length > 0" class="flex items-center justify-between py-2 border-t border-cream-deep/50 mt-4">
      <div class="text-sm text-muted-foreground">
        Hiển thị <span class="font-medium text-espresso">{{ (currentPage - 1) * itemsPerPage + 1 }}</span> - <span class="font-medium text-espresso">{{ Math.min(currentPage * itemsPerPage, filteredItems.length) }}</span> / <span class="font-medium text-espresso">{{ filteredItems.length }}</span> món
      </div>
      <div class="flex items-center gap-2">
        <Button 
          variant="outline"
          size="icon"
          @click="currentPage--" 
          :disabled="currentPage === 1"
          class="h-9 w-9 rounded-lg border-cream-deep disabled:opacity-50"
        >
          <ChevronLeft class="w-4 h-4" />
        </Button>
        <span class="text-sm font-semibold text-espresso px-3">
          Trang {{ currentPage }} / {{ totalPages }}
        </span>
        <Button 
          variant="outline"
          size="icon"
          @click="currentPage++" 
          :disabled="currentPage === totalPages"
          class="h-9 w-9 rounded-lg border-cream-deep disabled:opacity-50"
        >
          <ChevronRight class="w-4 h-4" />
        </Button>
      </div>
    </div>

    <!-- Edit/Add Modal (giữ nguyên, chỉ tăng shadow cho modal nếu component hỗ trợ) -->
    <Modal v-model="isOpen">
      <template #header>
        <h2 class="font-display text-3xl text-espresso">
          {{ editing && items.some(i => i.id === editing!.id) ? "Sửa món" : "Thêm món mới" }}
        </h2>
      </template>
      <div v-if="editing" class="space-y-6">
        <div class="space-y-1.5">
          <Label class="text-espresso">Tên món</Label>
          <Input v-model="editing.name" class="bg-background border border-cream-deep rounded-lg shadow-inner" placeholder="Vd: Cappuccino" />
        </div>
        <div class="space-y-1.5">
          <Label class="text-espresso">Mô tả</Label>
          <Textarea v-model="editing.description" class="bg-background border border-cream-deep rounded-lg shadow-inner min-h-[80px]" />
        </div>
        <div class="grid grid-cols-2 gap-4">
          <div class="space-y-1.5">
            <Label class="text-espresso">Giá (VND)</Label>
            <Input type="number" v-model.number="editing.price" class="bg-background border border-cream-deep rounded-lg shadow-inner" />
          </div>
          <div class="space-y-1.5">
            <Label class="text-espresso">Danh mục</Label>
            <select v-model="editing.category" class="flex h-11 w-full rounded-lg border border-cream-deep bg-background px-4 text-base shadow-inner focus-visible:outline-none">
              <option v-for="c in categories.filter(c => c.id !== 'all')" :key="c.id" :value="c.id">{{ c.label }}</option>
            </select>
          </div>
        </div>
        <div class="flex items-center justify-between p-4 rounded-lg bg-background border border-cream-deep shadow-inner">
          <div>
            <Label class="text-espresso">Đánh dấu Bán chạy</Label>
            <p class="text-xs text-muted-foreground mt-0.5">Hiển thị badge nổi bật cho khách</p>
          </div>
          <Switch v-model="editing.popular" />
        </div>
      </div>
      <template #footer>
        <Button variant="outline" @click="isOpen = false" class="border border-cream-deep rounded-lg">Hủy</Button>
        <Button @click="save" class="bg-caramel hover:bg-brown text-cream rounded-lg shadow-xl">Lưu</Button>
      </template>
    </Modal>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { Plus, Search, Edit3, Trash2, Flame, Coffee, ChevronLeft, ChevronRight } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import Label from '@/components/ui/Label.vue'
import Switch from '@/components/ui/Switch.vue'
import Textarea from '@/components/ui/Textarea.vue'
import Modal from '@/components/ui/Modal.vue'
import { menuItems as initial, formatVND, categories, type MenuItem, type Category } from '@/data/menu'

const toast = {
  success: (msg: string) => alert('Thành công: ' + msg),
  error: (msg: string) => alert('Lỗi: ' + msg)
}

const items = ref<MenuItem[]>([...initial])
const search = ref("")
const filter = ref<Category | "all">("all")
const editing = ref<MenuItem | null>(null)
const isOpen = ref(false)

const currentPage = ref(1)
const itemsPerPage = ref(8)

const filteredItems = computed(() => {
  return items.value.filter(m =>
    (filter.value === "all" || m.category === filter.value) &&
    m.name.toLowerCase().includes(search.value.toLowerCase())
  )
})

const totalPages = computed(() => Math.ceil(filteredItems.value.length / itemsPerPage.value) || 1)

const paginatedItems = computed(() => {
  const start = (currentPage.value - 1) * itemsPerPage.value
  return filteredItems.value.slice(start, start + itemsPerPage.value)
})

watch([search, filter], () => {
  currentPage.value = 1
})

const openNew = () => {
  editing.value = {
    id: `new-${Date.now()}`,
    name: "",
    description: "",
    price: 0,
    category: "coffee",
    image: items.value.length > 0 ? items.value[0].image : "",
    popular: false,
  }
  isOpen.value = true
}

const openEdit = (m: MenuItem) => {
  editing.value = { ...m }
  isOpen.value = true
}

const save = () => {
  if (!editing.value || !editing.value.name.trim()) {
    toast.error("Vui lòng nhập tên món")
    return
  }
 
  const index = items.value.findIndex(p => p.id === editing.value!.id)
  if (index !== -1) {
    items.value[index] = { ...editing.value }
  } else {
    items.value.unshift({ ...editing.value })
  }
 
  toast.success("Đã lưu món")
  isOpen.value = false
}

const remove = (id: string) => {
  items.value = items.value.filter((p) => p.id !== id)
  toast.success("Đã xóa món")
}
</script>
